### ISSUE TITLE
Build 할 때 Logback 관련 에러 발생

### ISSUE THREAD

**Issue by gitpher** [practicalProject8-A-5/Tiger-BE#10]
제가 오늘까지 마친 코드를 익현님과 맞춰보려고 했지만 처음엔 Test에 코드가 있어서 한 차례 Build를 실패했고, 다음엔 Build 하고 나서 EC2로 배포하려고 보니 아래와 같이 Logback 관련 에러가 났습니다. 아무래도 Logback 관련 설정들이 문제를 일으키는 것 같습니다. 빠른 시일 내에 이 문제를 같이 해결해보았으면 합니다. 

![image](https://user-images.githubusercontent.com/79530534/188452525-8d61fc0d-4c71-4b0b-bb27-1ca748486f5d.png)

**Comment by sungkong** [comment]
해결 완료!
